### PR TITLE
Makefile: Add (un)install targets

### PR DESCRIPTION
**Pull request by Pyrohh**
I figure we're already using a Makefile, so we might as well add these targets given people might expect them to be present.

### CODE REVIEW

**Comment by qbit** [comment]
Makes sense.

**Comment by jpouellet** [comment]
Feature creep imo. This is your package manager's job.

**Comment by Pyrohh** [comment]
> Feature creep imo

I'm not sure, maybe. It's probably easier for packagers to run `make install` inside their build script than manually invoking install(1). I suppose the main reason I sent this change was because of how ubiquitous `make install` is, but given how small the installation scope is I'm not sure it's worth it.

I wouldn't mind if you reverted this @qbit.

**Comment by jpouellet** [comment]
I mostly meant uninstall. I've never seen someone keep around the Makefile just to uninstall, and I've never seen a package manager that uses an uninstall target of a Makefile. It's small enough though, so I suppose it doesn't matter.

If consensus is that snap should also be in charge of updating itself (which I disagree with) then I think it makes sense to have this too, so I withdraw my comment.

**Comment by Pyrohh** [comment]
> If consensus is that snap should also be in charge of updating itself (which I disagree with) [snip]

Now that you mention it, I've always found it weird why that's a feature.
It seems like unneeded complexity, especially since snap is small enough that it won't be updated much.

**Comment by qbit** [comment]
Removed uninstall target. I agree that it is a bit excessive.

**Pull request merged**
