### PR TITLE
Add port Makefile

### LINKED ISSUE #41: Official package/port thoughts?
Are there any thoughts of getting this integrated into the OS itself? I managed to come up with my own package for it but its probably not ideal. I have not been using OpenBSD for a long time yet so my package is kind of hacky.

### PR DESCRIPTION
**Pull request by evitalis**
To learn how to build ports I created this for myself and figured I would share. Builds find and all files end up in the appropriate place. Resolves #41 as well.

### CODE REVIEW

**Comment by qbit** [comment]
Nice! I would recommend re-ordering things to be similar to [Makefile.template](http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/infrastructure/templates/Makefile.template?rev=1.77&content-type=text/plain). `REVISION` isn't needed. I will create some tarballs so we can avoid the use of `GH_*` variables.

I go back and forth about including `snap` as a port. It makes sense for -current, but having it in packages for a release would imply it can be used to upgrade releases, which isn't the case.

Maybe [openbsd-wip](https://github.com/jasperla/openbsd-wip) is the best place for it to live.

**Comment by evitalis** [comment]
@qbit Thanks for the suggestions. I went ahead and updated the order. 
I also had a debate about having a port for it for the same reasons. But I wanted an easier way of installing and updating it for myself. Plus it was an easy first port to write.

**Comment by evitalis** [comment]
Did you want me to move this to the other repo? Is it also correct that ports for -current are different than those in -stable? Still learning how that stuff is setup but since the documentation states to use the version of ports matching your branch it would make sense.

**Comment by qbit** [comment]
I think it makes more sense to have it in openbsd-wip. I could also make packages, similar to how landry@ does the firefox betas.

-stable ports are a snapshot of the ports cvs tree from around the time of release. Everything in the -current ports tree will eventually make it into -stable.

**Comment by evitalis** [comment]
I went ahead and moved the port to the requested repo. Feel free to close this when that PR is merged along with #41

**Comment by qbit** [comment]
Gonna close this as well :D - Once the project to support release is done, we can use these to get the port going a bit more.

**Pull request closed without merging**
